### ISSUE TITLE
Is it an Expense Tracker OR Cash-splitter

### ISSUE THREAD

**Issue by arhantbararia** [Siddhu2502/cash-splitter#8]
I just ran the program, There are serious implementation problems with this.

**Comment by Siddhu2502** [comment]
at the current state of this project it just tracks up all the expenses ... the entire project's base idea is that to split the bills when the person is in the progress ... eg: group of friends on a trip then a person can split all the money then and there .. the guy who has most money pays up then splits the bill 

at individual point of view it comes out as expense tracker .. when it comes to a group well then u split everything up
